src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_de_parution = null;

    #[ORM\Column]
    private ?int $nombre_de_pages = null;

    #[ORM\ManyToOne(inversedBy: 'livres')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Categorie $category = null;

    #[ORM\ManyToOne(inversedBy: 'livres')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Auteur $auteur = null;

    #[ORM\OneToMany(mappedBy: 'livre', targetEntity: Emprunt::class)]
    private Collection $emprunts;

    public function __construct()
    {
        $this->emprunts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNombreDePages(): ?int
    {
        return $this->nombre_de_pages;
    }

    public function setNombreDePages(int $nombre_de_pages): self
    {
        $this->nombre_de_pages = $nombre_de_pages;

        return $this;
    }

    public function getCategory(): ?Categorie
    {
        return $this->category;
    }

    public function setCategory(?Categorie $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getAuteur(): ?Auteur
    {
        return $this->auteur;
    }

    public function setAuteur(?Auteur $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    /**
     * @return Collection<int, Emprunt>
     */
    public function getEmprunts(): Collection
    {
        return $this->emprunts;
    }

    public function addEmprunt(Emprunt $emprunt): self
    {
        if (!$this->emprunts->contains($emprunt)) {
            $this->emprunts->add($emprunt);
            $emprunt->setLivre($this);
        }

        return $this;
    }

    public function removeEmprunt(Emprunt $emprunt): self
    {
        if ($this->emprunts->contains($emprunt)) {
            $emprunt->setLivre(null);
        }

        return $this;
    }

}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Auteur;
use App\Entity\Categorie;
use App\Entity\Livre;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('date_de_parution')
            ->add('nombre_de_pages')
            ->add('category', EntityType::class, [
                    'class'=>Categorie::class,
                    'choice_label' => 'nom'
            ])
            ->add('auteur', EntityType::class, [
                'class'=>Auteur::class,
                'choice_label' => 'nom'
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/livre')]
class LivreController extends AbstractController
{
    #[Route('/', name: 'app_livre_index', methods: ['GET'])]
    public function index(LivreRepository $livreRepository, Request $request): Response
    {
        $auteur = $request->query->get('auteur');

        $livres = [];
        if ($auteur) {
            // Recherche des livres par auteur
            $livres = $livreRepository->findByAuteur($auteur);
        } else {
            // Récupération de tous les livres
            $livres = $livreRepository->findAll();
        }

        return $this->render('livre/index.html.twig', [
            'livres' => $livres,
        ]);
    }

    #[Route('/new', name: 'app_livre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, LivreRepository $livreRepository): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $livreRepository->save($livre, true);

            return $this->redirectToRoute('app_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_livre_show', methods: ['GET'])]
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_livre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Livre $livre, LivreRepository $livreRepository): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $livreRepository->save($livre, true);

            return $this->redirectToRoute('app_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_livre_delete', methods: ['POST'])]
    public function delete(Request $request, Livre $livre, LivreRepository $livreRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            // Dissociate loans from the book
            foreach ($livre->getEmprunts() as $emprunt) {
                $livre->removeEmprunt($emprunt);
                $emprunt->setLivre(null);
            }

            // Remove the book
            $livreRepository->remove($livre, true);
        }

        return $this->redirectToRoute('app_livre_index', [], Response::HTTP_SEE_OTHER);
    }



}

templates/livre/_delete_form.html.twig
<form method="post" action="{{ path('app_livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/livre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre{% endblock %}

{% block body %}
    <h1>Edit Livre</h1>

    {{ include('livre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_livre_index') }}">back to list</a>

    {{ include('livre/_delete_form.html.twig') }}
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre index{% endblock %}

{% block body %}
    <h1>Livre index</h1>

    <form action="{{ path('app_livre_index') }}" method="get">
        <div class="form-group">
            <label for="auteur">Recherche par auteur :</label>
            <input type="text" id="auteur" name="auteur" class="form-control" value="{{ app.request.query.get('auteur') }}">
        </div>
        <button type="submit" class="btn btn-primary">Rechercher</button>
    </form>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Date_de_parution</th>
            <th>Nombre_de_pages</th>
            <th>Categorie</th>
            <th>Auteur</th>
            <th>Nombre d'emprunts</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for livre in livres %}
            <tr>
                <td>{{ livre.id }}</td>
                <td>{{ livre.titre }}</td>
                <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ livre.nombreDePages }}</td>

                {% if livre.category.nom is defined %}
                    <td>{{ livre.category.nom }}</td>
                {% else %}
                    <td>(supprimé)</td>
                {% endif %}
                <td>{{ livre.auteur.nom }}</td>
                <td>{{ livre.emprunts|length }}</td>
                <td>
                    <a href="{{ path('app_livre_show', {'id': livre.id}) }}">show</a>
                    <a href="{{ path('app_livre_edit', {'id': livre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_livre_new') }}">Create new</a>
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre{% endblock %}

{% block body %}
    <h1>Create new Livre</h1>

    {{ include('livre/_form.html.twig') }}

    <a href="{{ path('app_livre_index') }}">back to list</a>
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre{% endblock %}

{% block body %}
    <h1>Livre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ livre.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ livre.titre }}</td>
            </tr>
            <tr>
                <th>Date_de_parution</th>
                <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre_de_pages</th>
                <td>{{ livre.nombreDePages }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ livre.category.nom }}</td>
            </tr>
            <tr>
                <th>Auteur</th>
                <td>{{ livre.auteur.nom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_livre_index') }}">back to list</a>

    <a href="{{ path('app_livre_edit', {'id': livre.id}) }}">edit</a>

    {{ include('livre/_delete_form.html.twig') }}
{% endblock %}