src/Entity/Adherent.php
<?php

namespace App\Entity;

use App\Repository\AdherentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdherentRepository::class)]
class Adherent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_inscription = null;

    #[ORM\OneToMany(mappedBy: 'adherent', targetEntity: Emprunt::class, cascade: ['remove'])]
    private Collection $emprunts;

    public function __construct()
    {
        $this->emprunts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    /**
     * @return Collection<int, Emprunt>
     */
    public function getEmprunts(): Collection
    {
        return $this->emprunts;
    }

    public function addEmprunt(Emprunt $emprunt): self
    {
        if (!$this->emprunts->contains($emprunt)) {
            $this->emprunts->add($emprunt);
            $emprunt->setAdherent($this);
        }

        return $this;
    }

    public function removeEmprunt(Emprunt $emprunt): self
    {
        if ($this->emprunts->removeElement($emprunt)) {
            // set the owning side to null (unless already changed)
            if ($emprunt->getAdherent() === $this) {
                $emprunt->setAdherent(null);
            }
        }

        return $this;
    }
}

src/Form/AdherentType.php
<?php

namespace App\Form;

use App\Entity\Adherent;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdherentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('email')
            ->add('date_inscription')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Adherent::class,
        ]);
    }
}

src/Controller/AdherentController.php
<?php

namespace App\Controller;

use App\Entity\Adherent;
use App\Form\AdherentType;
use App\Repository\AdherentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/adherent')]
class AdherentController extends AbstractController
{
    #[Route('/', name: 'app_adherent_index', methods: ['GET'])]
    public function index(AdherentRepository $adherentRepository): Response
    {
        return $this->render('adherent/index.html.twig', [
            'adherents' => $adherentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_adherent_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AdherentRepository $adherentRepository): Response
    {
        $adherent = new Adherent();
        $form = $this->createForm(AdherentType::class, $adherent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $adherentRepository->save($adherent, true);

            return $this->redirectToRoute('app_adherent_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adherent/new.html.twig', [
            'adherent' => $adherent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_adherent_show', methods: ['GET'])]
    public function show(Adherent $adherent): Response
    {
        return $this->render('adherent/show.html.twig', [
            'adherent' => $adherent,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_adherent_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Adherent $adherent, AdherentRepository $adherentRepository): Response
    {
        $form = $this->createForm(AdherentType::class, $adherent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $adherentRepository->save($adherent, true);

            return $this->redirectToRoute('app_adherent_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adherent/edit.html.twig', [
            'adherent' => $adherent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_adherent_delete', methods: ['POST'])]
    public function delete(Request $request, Adherent $adherent, AdherentRepository $adherentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adherent->getId(), $request->request->get('_token'))) {
            $adherentRepository->remove($adherent, true);
        }

        return $this->redirectToRoute('app_adherent_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/adherent/_delete_form.html.twig
<form method="post" action="{{ path('app_adherent_delete', {'id': adherent.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adherent.id) }}">
    <button class="btn">Delete</button>
</form>

templates/adherent/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/adherent/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Adherent{% endblock %}

{% block body %}
    <h1>Edit Adherent</h1>

    {{ include('adherent/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_adherent_index') }}">back to list</a>

    {{ include('adherent/_delete_form.html.twig') }}
{% endblock %}

templates/adherent/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adherent index{% endblock %}

{% block body %}
    <h1>Adherent index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Email</th>
                <th>Date_inscription</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for adherent in adherents %}
            <tr>
                <td>{{ adherent.id }}</td>
                <td>{{ adherent.nom }}</td>
                <td>{{ adherent.prenom }}</td>
                <td>{{ adherent.email }}</td>
                <td>{{ adherent.dateInscription ? adherent.dateInscription|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_adherent_show', {'id': adherent.id}) }}">show</a>
                    <a href="{{ path('app_adherent_edit', {'id': adherent.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_adherent_new') }}">Create new</a>
{% endblock %}

templates/adherent/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Adherent{% endblock %}

{% block body %}
    <h1>Create new Adherent</h1>

    {{ include('adherent/_form.html.twig') }}

    <a href="{{ path('app_adherent_index') }}">back to list</a>
{% endblock %}

templates/adherent/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adherent{% endblock %}

{% block body %}
    <h1>Adherent</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ adherent.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ adherent.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ adherent.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ adherent.email }}</td>
            </tr>
            <tr>
                <th>Date_inscription</th>
                <td>{{ adherent.dateInscription ? adherent.dateInscription|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_adherent_index') }}">back to list</a>

    <a href="{{ path('app_adherent_edit', {'id': adherent.id}) }}">edit</a>

    {{ include('adherent/_delete_form.html.twig') }}
{% endblock %}